### PR TITLE
:new: Support multipart request

### PR DESCRIPTION
**Pull request by tyx**
Replace #93

### CODE REVIEW

**Comment by tyx** [comment]
it's green, what do you think about the change @bystro ?

If it's good for you, I can merge and let you test on dev-master until we release a new version next week after your approval ?

**Comment by bystro** [comment]
I like it but I think we should communicate it more like posting request as a html form - I added some comments in commit's code.

**Comment by bystro** [comment]
You can merge it into dev-master. I will test it on Monday.

**Comment by bystro** [comment]
You could merge it to master-dev branch first.

**Pull request merged**
