### PR TITLE
#87 Step: When I attach the following files:

### PR DESCRIPTION
**Pull request by bystro**
I have tested the code with ZendFramework's AbstractRestfulControlle and tests passed 
https://github.com/zendframework/zend-mvc/blob/master/src/Controller/AbstractRestfulController.php

Checkout this code and test it with your RestFul frameworks.

I have replaced php-http/curl-client with php-http/guzzle6-adapter because PSR-7 aware client is required. 
https://github.com/ubirak/rest-api-behat-extension/compare/master...bystro:87WhenIattachfiles#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R40
Do I should force using Guzzle using useHttpClient() method?
https://github.com/ubirak/rest-api-behat-extension/compare/master...bystro:87WhenIattachfiles#diff-9d1a35b8dac9c540c2aedf7c51d8e7e7R112

I made header's name lower case, because I have to be sure if content-type header has 'multipart/form-data' value.
https://github.com/ubirak/rest-api-behat-extension/compare/master...bystro:87WhenIattachfiles#diff-9d1a35b8dac9c540c2aedf7c51d8e7e7R151
https://github.com/ubirak/rest-api-behat-extension/compare/master...bystro:87WhenIattachfiles#diff-9d1a35b8dac9c540c2aedf7c51d8e7e7R164
HTTP/1.1 specification says that names are case-insensitive.

I see that the $body param of sendRequest() method may be an array type. 
https://github.com/ubirak/rest-api-behat-extension/compare/master...bystro:87WhenIattachfiles#diff-9d1a35b8dac9c540c2aedf7c51d8e7e7R100
For sure? Is there a case of using it as array in the project?
If so I should handle this here
https://github.com/ubirak/rest-api-behat-extension/compare/master...bystro:87WhenIattachfiles#diff-9d1a35b8dac9c540c2aedf7c51d8e7e7R210

### CODE REVIEW

**Comment by tyx** [comment]
any chance to rollback all identation changes to make easier the review ?

**Comment by bystro** [comment]
I haven't change identations. Why it happend?

**Comment by tyx** [comment]
I guess your IDE/Editor did it on its own ;)

**Comment by bystro** [comment]
I made changes in Netbeans. I'll try to make changes in "plain/text" editor and will pull new pull request.

**Pull request closed without merging**
