### PR TITLE
Allow to use symfony/property-access > 5.0

### PR DESCRIPTION
**Pull request by gmorel**
#### Pain Point

In order to fix

```
Problem 1
    - Root composer.json requires ubirak/rest-api-behat-extension ^8.0 -> satisfiable by ubirak/rest-api-behat-extension[8.0.0].
    - ubirak/rest-api-behat-extension 8.0.0 requires symfony/property-access ~4.0 -> found symfony/property-access[v4.0.0-BETA1, ..., v4.4.20] but it conflicts with your root composer.json require (5.2.*).
```

#### TODO 

- [x] Take the same range as `symfony/config` and `symfony/dependency-injection`. Unless there was a reason ?
- [x] Reorder so we no more forget it

Keep up the good work

### CODE REVIEW

**Review by tyx — APPROVED** [review]

**Review by tyx — APPROVED** [review]

**Comment by gmorel** [comment]
Thanks @tyx.
Small question, since behatch is kinda dead since read only. Do you use another alternative?

**Comment by tyx** [comment]
We no longer use this extension indeed ! 

In fact, we no longer make http request with behat ;)

**Comment by gmorel** [comment]
What are you using ?

**Comment by tyx** [comment]
nothing ;) We don't make real http request for now. Only kernel request.

**Comment by gmorel** [comment]
Behavior Tests as fast as Unit Tests

Lucky you :+1:

**Comment by tyx** [comment]
image

;)

**Pull request merged**
