### PR TITLE
Update dependencies for php8 compatibility

### PR DESCRIPTION
**Pull request by adalessa**
Updating a project to use PHP 8, failed due the dependencies `php-http/client-common` and `php-http/guzzle6-adapter` hold back to PHP 7. 
Updating them allow it to be use with php 8, and local test still running.

### CODE REVIEW

**Comment by Spy-Seth** [comment]
The proposed package seems not compatible with PHP 7. @tyx wdyt?

**Comment by tyx** [comment]
a new major version can be envisaged to support php8 !

**Comment by tyx** [comment]
We need to update the .travis.yml by adding php8 to the matrice to ensure this PR is ok.

**Comment by adalessa** [comment]
Thanks for the replies. I have been testing and I have updated travis with what I believe is a valid configuration, and I have updated the requirements to be compatible in all the expected forms for versions of PHP 7.2, 7.3, 7.4 and of course 8.0

**Comment by tyx** [comment]
It looks great ! Thanks a lot @adalessa !

**Review by tyx — APPROVED** [review]

**Pull request merged**
